### ISSUE TITLE
Error on loading the oboobs cog.

### ISSUE THREAD

**Issue by blimey85** [Canule/Mash-Cogs#14]
I'm able to install the repo and the cog but I get the following when I try to load the cog. Is this only for v3 now?

```bash
Nov 13 00:23:00 tbc python3[21595]: Copying oboobs...
Nov 13 00:23:03 tbc python3[21595]: [13/11/2018 00:23] ERROR owner load 74: No module named 'redbot'
Nov 13 00:23:03 tbc python3[21595]: Traceback (most recent call last):
Nov 13 00:23:03 tbc python3[21595]:   File "/home/gary/Red-DiscordBot/cogs/owner.py", line 65, in load
Nov 13 00:23:03 tbc python3[21595]:     self._load_cog(module)
Nov 13 00:23:03 tbc python3[21595]:   File "/home/gary/Red-DiscordBot/cogs/owner.py", line 946, in _load_cog
Nov 13 00:23:03 tbc python3[21595]:     mod_obj = importlib.import_module(cogname)
Nov 13 00:23:03 tbc python3[21595]:   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
Nov 13 00:23:03 tbc python3[21595]:     return _bootstrap._gcd_import(name[level:], package, level)
Nov 13 00:23:03 tbc python3[21595]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Nov 13 00:23:03 tbc python3[21595]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Nov 13 00:23:03 tbc python3[21595]:   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
Nov 13 00:23:03 tbc python3[21595]:   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
Nov 13 00:23:03 tbc python3[21595]:   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
Nov 13 00:23:03 tbc python3[21595]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Nov 13 00:23:03 tbc python3[21595]:   File "/home/gary/Red-DiscordBot/cogs/oboobs.py", line 3, in <module>
Nov 13 00:23:03 tbc python3[21595]:     from redbot.core import checks, Config
Nov 13 00:23:03 tbc python3[21595]: ModuleNotFoundError: No module named 'redbot'
```

**Comment by Fr6jDJF** [comment]
Reverted, merged at wrong branch, should work again v2
